version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=smarty
      - POSTGRES_PASSWORD=smarty
      - POSTGRES_DB=smarty
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
